import { test, expect } from "@playwright/test";
import { readFile } from "node:fs/promises";
const input = JSON.parse(await readFile(process.env.LIVE_BROWSER_MANIFEST,"utf8"));
test("new CSV -> original RAW -> explicit resolution -> manual review, without seeding commands",async({page})=>{
  const errors=[];page.on("pageerror",error=>errors.push(error.message));
  await page.goto("/ingest");
  const form=page.getByRole("form",{name:"接入 CSV"});
  await form.getByLabel("数据集名称").fill(input.name);
  await form.getByLabel("数据来源说明").fill("本次浏览器验收动态生成的合成 CSV，不是仓库内置样本。");
  await form.getByLabel("本次处理用途").fill("验证界面接入、原始字节留存与人工审核。");
  await form.getByRole("checkbox").check();
  await form.getByLabel("选择 CSV 文件").setInputFiles({name:"invalid.csv",mimeType:"text/csv",buffer:Buffer.from("source_company_id,company_name\na,b,c")});
  await expect(form.getByRole("alert")).toContainText("第 2 行");
  await expect(form.getByRole("button",{name:"登记来源并保存 RAW 版本"})).toBeDisabled();
  await form.getByLabel("选择 CSV 文件").setInputFiles({name:"operator-selected.csv",mimeType:"text/csv",buffer:Buffer.from(input.csvText)});
  await expect(page.getByText(/CSV 预检通过：2 条记录/)).toBeVisible();
  await page.screenshot({path:test.info().outputPath("01-preview.png"),fullPage:true});
  await form.getByRole("button",{name:"登记来源并保存 RAW 版本"}).click();
  await expect(page.getByRole("status").filter({hasText:"原始 CSV 已保存为 RAW 版本"})).toBeVisible();
  const rawURL=await page.getByRole("link",{name:"查看 RAW 数据集与版本"}).getAttribute("href");
  const resumeURL=await page.getByRole("link",{name:"保存此入口，稍后继续解析"}).getAttribute("href");
  await page.screenshot({path:test.info().outputPath("02-raw-created.png"),fullPage:true});
  await page.goto(resumeURL);
  const resolution=page.getByRole("form",{name:"启动主体解析"});
  await expect(resolution.getByRole("button")).toBeDisabled();
  await resolution.getByRole("checkbox").check();
  await resolution.getByRole("button").click();
  await expect(page.getByRole("status").filter({hasText:"WAITING_REVIEW"})).toBeVisible();
  await page.getByRole("link",{name:"进入实体审核队列"}).click();
  const reviews=page.getByRole("form",{name:/^审核 /});
  await expect(reviews).toHaveCount(1);
  await page.screenshot({path:test.info().outputPath("03-review.png"),fullPage:true});
  await reviews.getByLabel("审核理由（必填）").fill(input.reason);
  await reviews.getByRole("button",{name:"确认匹配"}).click();
  await expect(reviews).toHaveCount(0);
  await page.goto(rawURL);
  await page.getByRole("link",{name:"继续主体解析"}).click();
  await page.getByRole("form",{name:"启动主体解析"}).getByRole("checkbox").check();
  await page.getByRole("button",{name:"启动解析并进入审核"}).click();
  await expect(page.getByRole("alert")).toContainText("此版本已有解析输出容器");
  await expect(page.getByRole("button",{name:"启动解析并进入审核"})).toBeDisabled();
  await page.getByRole("link",{name:"查看解析输出数据集"}).click();
  await expect(page.getByRole("heading",{name:"不可变版本历史"})).toBeVisible();
  await page.screenshot({path:test.info().outputPath("04-resolved-version.png"),fullPage:true});
  expect(errors).toEqual([]);
});
